language: python

os:
    - linux

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

script: 
    - ./try_autotools.sh
    - ./clean.sh
    - ./try_setup_py.sh

notifications:
  email: false

